apiVersion: v1
data:
  fluentd.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match>
      @type loki
      url "http://loki:3100"
      extra_labels {"agent": "fluentd"}
      <label>
        service_name $.service
        instance_id $.instance_id
      </label>
      <buffer>
        flush_internal 10s
        flush_at_shutdown true
        chunk_limit_size 1m
      </buffer>
    </match>
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: fluentd
  name: fluentd-cm0
