apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - args:
            - -config.file=/etc/loki/local-config.yaml
          image: grafana/loki:main
          name: loki
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/loki/local-config.yaml
              name: loki-cm0
              subPath: local-config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: loki-config.yaml
                path: local-config.yaml
            name: loki-cm0
          name: loki-cm0
