apiVersion: v1
data:
  init.sql: |
    CREATE DATABASE user_service_db;
    CREATE DATABASE plant_service_db;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db
  name: db-cm1
