apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: main-app
  name: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: main-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: main-app
    spec:
      containers:
        - args:
            - python
            - main_app.py
          image: lynnmombarg/greenhouse-main_app
          name: main-app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
