apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: websocket-service
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: websocket-service
    spec:
      containers:
        - args:
            - python
            - websocket_service.py
          image: lynnmombarg/greenhouse-websocket_service
          name: websocket-service
          ports:
            - containerPort: 5004
              protocol: TCP
      restartPolicy: Always
